version: 2.1
aliases:
  - &restore_gem_cache
    name: Restore cache
    keys:
      - jars-{{ checksum "build.gradle" }}-{{ checksum "app/build.gradle" }}

  - &save_gem_cache
    name: Saving cache
    key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
    paths:
      - ~/.gradle

  - &attach_workspace
    attach_workspace:
      at: ~/code

  - &download_dep
    - checkout
    - *attach_workspace
    - run:
        name: Download Dependencies
        command: |
          sudo chmod +x gradlew
          ./gradlew androidDependencies

  - &run_lint
    - checkout
    - *attach_workspace
    - restore_cache: *restore_gem_cache
    - run:
        name: Run Lint
        command: ./gradlew lintDebug
    - save_cache: *save_gem_cache

  - &run_unit_tests
    - checkout
    - *attach_workspace
    - run:
        name: Run Unit Tests
        command: ./gradlew testDebugUnitTest

  - &assembleDebug
    - checkout
    - *attach_workspace
    - run:
        name: Build Debug
        command: ./gradlew assembleDebug
    - store_artifacts:
        path: app/build/outputs/apk/debug/app-debug.apk
        destination: app-debug.apk

  - &deployToBintray
    - checkout
    - *attach_workspace
    - run:
        name: Install
        command: ./gradlew install
    - run:
        name: Bintray Upload
        command: ./gradlew bintrayUpload


  - &deploy_environment
    working_directory: ~/code
    docker:
      - image: circleci/android:api-29
  - &test_environment
    working_directory: ~/code
    docker:
      - image: circleci/android:api-29


  # dependency groups
  - &prepare_sources
    - "Prepared_Sources"

  - &all_test
    - "Run_Lint"
    - "Run_Unit_Tests"

  - &debug_build
    - "Assemble_Debug_Build"

jobs:
  "Prepared_Sources":
    <<: *test_environment
    environment:
      JVM_OPTS: -Xmx3200m
    steps: *download_dep

  "Run_Lint":
    <<: *test_environment
    environment:
      JVM_OPTS: -Xmx3200m
    steps: *run_lint

  "Run_Unit_Tests":
    <<: *test_environment
    environment:
      JVM_OPTS: -Xmx3200m
    steps: *run_unit_tests

  "Assemble_Debug_Build":
    <<: *test_environment
    environment:
      JVM_OPTS: -Xmx3200m
    steps: *assembleDebug

  "Deploy_to_Bintray":
    <<: *test_environment
    environment:
      JVM_OPTS: -Xmx3200m
    steps: *deployToBintray



workflows:
  version: 2.1
  main:
    jobs:
      - "Prepared_Sources":
          filters:
            branches:
              only:
                - master
                - stage
                - develop
      - "Run_Lint":
          requires:
            *prepare_sources
          filters:
            branches:
              only:
                - master
                - stage
      - "Run_Unit_Tests":
          requires:
            *prepare_sources
          filters:
            branches:
              only:
                - master
                - stage
                - develop
      - "Assemble_Debug_Build":
          requires:
            *all_test
          filters:
            branches:
              only:
                - master
                - stage
#      - "Deploy to Bintray":
#          requires:
#            *debug_build
#          filters:
#            branches:
#              only:
#                - master

