package com.verygoodsecurity.vgscollect.core.model.state.tokenization

enum class VGSVaultAliasFormat {

    FPE_ACC_NUM_T_FOUR,
    FPE_ALPHANUMERIC_ACC_NUM_T_FOUR,
    FPE_SIX_T_FOUR,
    FPE_SSN_T_FOUR,
    FPE_T_FOUR,
    NUM_LENGTH_PRESERVING,
    PFPT,
    RAW_UUID,
    UUID,
    GENERIC_T_FOUR,
    ALPHANUMERIC_SIX_T_FOUR,
    ALPHANUMERIC_LENGTH_PRESERVING,
    ALPHANUMERIC_LENGTH_PRESERVING_T_FOUR,
    ALPHANUMERIC_SSN_T_FOUR,
    ALPHANUMERIC_LENGTH_PRESERVING_SIX_T_FOUR,
}