package com.verygoodsecurity.vgscollect

enum class VGSError(val code:Int) {
    INPUT_DATA_REQUARED(1001),
    INPUT_DATA_REQUARED_VALID_ONLY(1002),
    INPUT_FILE_SIZE_EXCEEDS_THE_LIMIT(1101),
    INPUT_FILE_TYPE_IS_WRONG(1102),
    INPUT_FILE_TYPE_IS_NOT_SUPPORTED(1103),
    INPUT_FILE_NOT_FOUND(1103)
}