name: Mirror to Public Repository

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - 'public/*' # for testing purposes
    tags:
      - "*"

jobs:
  mirror:
    name: Mirror Repository
    uses: verygood-ops/cicd-shared/.github/workflows/public-mirror.yaml@f1a734b2642649c8e9188cf7bc2505db5bb01e27 # public-mirror-workflow-v1.0.0
    secrets:
      VGS_GITHUB_CI_BOT_APP_ID: ${{ secrets.VGS_GITHUB_CI_BOT_APP_ID }}
      VGS_GITHUB_CI_BOT_APP_PEM_FILE: ${{ secrets.VGS_GITHUB_CI_BOT_APP_PEM_FILE }}
